"""Chat HTTP + SSE routes for the Web channel.

Surface area:

- ``POST /api/chat/send`` — accept a user message, feed the debounce
  state machine on the in-process ``WebChannel``
- ``GET /api/chat/events`` — long-lived SSE stream; every connected
  browser tab holds exactly one of these, and all channel events fan
  out through this endpoint
- ``GET /api/chat/voice/{message_id}.mp3`` — serve cached voice files
  generated by the voice service

Admin endpoints live in a sibling router and mount on the same
FastAPI app. This module is deliberately chat-only so the admin
surface never leaks into it.

The router is built by :func:`build_chat_router` which takes the live
``WebChannel`` and ``SSEBroadcaster`` references and closes over them
inside the handler functions. The handlers never reach into a global
registry — everything is passed in explicitly so tests can build a
fresh router against a fresh channel in isolation.
"""

from __future__ import annotations

import asyncio
import logging
from datetime import datetime
from typing import Any

from fastapi import APIRouter, HTTPException, status
from pydantic import BaseModel, Field
from sse_starlette.sse import EventSourceResponse, ServerSentEvent

from echovessel.channels.base import IncomingMessage
from echovessel.channels.web.channel import WebChannel
from echovessel.channels.web.sse import SSEBroadcaster

log = logging.getLogger(__name__)


class ChatSendRequest(BaseModel):
    """Request body for ``POST /api/chat/send``."""

    content: str = Field(..., min_length=1, max_length=20_000)
    user_id: str = Field(default="self", max_length=128)
    external_ref: str | None = Field(default=None, max_length=256)


def build_chat_router(
    *,
    channel: WebChannel,
    broadcaster: SSEBroadcaster,
    voice_service: Any | None = None,
) -> APIRouter:
    """Wire chat endpoints onto a new :class:`APIRouter`.

    Everything is bound through closures over ``channel``,
    ``broadcaster``, and (optionally) ``voice_service``. Tests can call
    this directly with a fresh WebChannel instance and mount the router
    on a fresh FastAPI app without any global state.

    Stage 7 added ``voice_service`` so the
    ``GET /api/chat/voice/{message_id}.mp3`` endpoint can locate the
    voice cache directory. When ``voice_service is None`` (voice
    disabled in config), the endpoint returns 404.
    """

    router = APIRouter(prefix="/api/chat", tags=["chat"])

    @router.post(
        "/send",
        status_code=status.HTTP_202_ACCEPTED,
    )
    async def send(req: ChatSendRequest) -> dict[str, Any]:
        """Accept one user message and feed the debounce state machine.

        The response is ``202 Accepted`` because assembly and streaming
        happen asynchronously — the actual persona reply arrives on the
        SSE stream, not as the body of this response.
        """

        msg = IncomingMessage(
            channel_id=channel.channel_id,
            user_id=req.user_id,
            content=req.content,
            received_at=datetime.now(),
            external_ref=req.external_ref,
        )
        try:
            await channel.push_user_message(msg)
        except Exception as e:  # noqa: BLE001
            log.error("push_user_message failed: %s", e, exc_info=True)
            raise HTTPException(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                detail=f"channel rejected message: {e}",
            ) from e
        return {"ok": True}

    @router.get("/events")
    async def events() -> EventSourceResponse:
        """Long-lived SSE stream for this client.

        On connection we push a ``chat.connection.ready`` frame so the
        client can seed its UI state (voice toggle, etc.) before any
        later broadcast arrives. Disconnect is detected by the generator
        raising ``asyncio.CancelledError`` — ``finally`` unregisters the
        client queue.
        """

        queue = await broadcaster.register()
        # Seed the stream so clients don't sit silent on first connect.
        await queue.put(
            {
                "event": "chat.connection.ready",
                "data": {"channel_id": channel.channel_id},
            }
        )

        async def _stream():
            try:
                while True:
                    frame = await queue.get()
                    yield ServerSentEvent(
                        event=frame["event"],
                        data=_json_dump(frame["data"]),
                    )
            except asyncio.CancelledError:
                raise
            finally:
                await broadcaster.unregister(queue)

        return EventSourceResponse(_stream())

    # ------------------------------------------------------------------
    # Voice file serving
    # ------------------------------------------------------------------

    @router.get("/voice/{message_id}.mp3")
    async def get_voice_file(message_id: int):  # noqa: D401
        """Serve a cached voice file generated by ``VoiceService.generate_voice``.

        The file lives at ``<voice_cache_dir>/<message_id>.mp3``. Returns
        404 when voice is not configured, the file was never generated,
        or the cache was cleared.

        Cache-Control is ``immutable`` because the URL contains the
        ``message_id`` — the content never changes once written. Browsers
        and proxies can hold the file for as long as they want.
        """
        from pathlib import Path

        from fastapi.responses import FileResponse

        if voice_service is None:
            raise HTTPException(
                status_code=404,
                detail="voice service not configured",
            )
        cache_dir = getattr(voice_service, "_voice_cache_dir", None)
        if cache_dir is None:
            raise HTTPException(
                status_code=404,
                detail="voice cache directory not available",
            )
        cache_path = Path(cache_dir) / f"{message_id}.mp3"
        if not cache_path.exists():
            raise HTTPException(
                status_code=404,
                detail="voice file not found",
            )
        return FileResponse(
            path=cache_path,
            media_type="audio/mpeg",
            filename=f"{message_id}.mp3",
            headers={
                "Cache-Control": "public, max-age=31536000, immutable",
            },
        )

    return router


def _json_dump(data: dict) -> str:
    """Serialize an event payload to a JSON string for the SSE frame.

    Kept in this module so tests can monkeypatch / import it without
    pulling in the full router. The ``ServerSentEvent.data`` field is
    a plain string on the wire — sse_starlette does not do JSON
    encoding for us.
    """

    import json

    return json.dumps(data, default=str, ensure_ascii=False)
