"""Channel Protocol v0.2 — canonical envelope types + Protocol shape.

This module is the authoritative home for the envelope types that cross
the channel ↔ runtime boundary. Previous revisions duplicated the types
inside ``runtime/interaction.py``; v0.2 consolidates them here so the
layered architecture (`runtime → channels → memory|voice → core`) is
honoured at the module level and Thread WEB-stage1 can upgrade the
contract without importing backwards into the runtime package.

The shape is driven by the Stage 1 tracker at
``develop-docs/web-v1/01-stage-1-tracker.md`` and spec §2.2 / §2.3a of
``develop-docs/channels/01-spec-v0.1.md``. The key additions over v0.1:

- ``IncomingTurn`` — a debounced burst of ``IncomingMessage`` objects
  that channels emit instead of individual messages
- ``OutgoingMessage`` — the typed envelope runtime hands to
  ``Channel.send``, carrying ``in_reply_to_turn_id`` / ``kind`` /
  ``delivery``
- ``Channel.on_turn_done`` — runtime callback so the channel's debounce
  state machine can promote ``next_turn`` into ``current_turn`` via a
  **normal** debounce cycle (review M1 iron rule)

``push_sse`` is deliberately NOT on the Protocol. Some channels (the web
channel) implement it as an optional capability method; runtime detects
it with ``getattr(channel, "push_sse", None)``.
"""

from __future__ import annotations

import uuid
from collections.abc import AsyncIterator
from dataclasses import dataclass
from datetime import datetime
from typing import TYPE_CHECKING, Literal, Protocol, runtime_checkable

if TYPE_CHECKING:
    # Channel code is Layer 3; voice is Layer 2. Importing the concrete
    # VoiceResult class here would be legal per the layered contract
    # (runtime → channels → memory|voice → core), but we keep it under
    # TYPE_CHECKING anyway so a fresh channel consumer doesn't pay the
    # voice-package import cost on module load. Stage 7 added this
    # field so channels can forward pre-generated voice artifacts
    # through the send path without each channel having to re-run
    # generate_voice itself.
    from echovessel.voice.models import VoiceResult

# ---------------------------------------------------------------------------
# Envelope dataclasses
# ---------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class IncomingMessage:
    """One raw user message, the leaf unit within an ``IncomingTurn``.

    This is still the object runtime forwards (field-for-field) into
    ``memory.ingest_message`` — the frozen layout therefore also constitutes
    memory's durable column contract for L2 ``recall_messages``.

    Fields:
        channel_id: stable opaque channel id (see spec §2.3)
        user_id: internal user id; MVP always ``"self"``
        content: plain text; attachments are deferred to v1.x
        received_at: wall-clock timestamp at ingest (runtime may override
            during replay)
        external_ref: optional channel-native correlation id the channel
            uses to thread outgoing replies back to the originating
            message (Discord reference, iMessage GUID, SSE client tag, …)
        turn_id: back-pointer to the enclosing :class:`IncomingTurn`.
            Channels that debounce populate this at flush time; memory
            mirrors it on ``recall_messages.turn_id`` so L2 readers can
            group a burst without re-running debounce.
    """

    channel_id: str
    user_id: str
    content: str
    received_at: datetime
    external_ref: str | None = None
    turn_id: str | None = None


@dataclass(frozen=True, slots=True)
class IncomingTurn:
    """A debounced group of :class:`IncomingMessage` objects.

    Channels emit ``IncomingTurn`` instead of individual messages so the
    runtime turn loop sees exactly **one** shape per LLM invocation.
    ``len(messages) == 1`` is the degenerate single-message case — it
    still arrives wrapped in an ``IncomingTurn``; there is no separate
    ``IncomingMessage`` code path in the consumer.

    Invariants:

    - ``messages`` is non-empty and time-ordered
    - Every message in ``messages`` shares the same ``channel_id`` and
      ``user_id``
    - ``turn_id`` is generated by the channel at flush time and is
      mirrored onto each wrapped ``IncomingMessage.turn_id``
    """

    turn_id: str
    channel_id: str
    user_id: str
    messages: list[IncomingMessage]
    received_at: datetime

    @classmethod
    def from_single_message(
        cls,
        msg: IncomingMessage,
        *,
        turn_id: str | None = None,
    ) -> IncomingTurn:
        """Wrap a single :class:`IncomingMessage` into a 1-element turn.

        Used by channels that do not debounce (tests, CLI, future
        adapter shims) and by the runtime compatibility path for legacy
        test stubs. A fresh ``turn_id`` is generated when the caller
        does not supply one; the wrapped message carries the same id on
        its ``turn_id`` field so downstream memory writes stay linked.
        """

        tid = turn_id or f"turn-{uuid.uuid4().hex[:12]}"
        wrapped = IncomingMessage(
            channel_id=msg.channel_id,
            user_id=msg.user_id,
            content=msg.content,
            received_at=msg.received_at,
            external_ref=msg.external_ref,
            turn_id=tid,
        )
        return cls(
            turn_id=tid,
            channel_id=msg.channel_id,
            user_id=msg.user_id,
            messages=[wrapped],
            received_at=msg.received_at,
        )


# ---------------------------------------------------------------------------
# Outgoing — what runtime hands to Channel.send()
# ---------------------------------------------------------------------------


OutgoingKind = Literal["reply", "proactive"]
"""Whether a send is a normal turn reply or a proactive push.

Front-ends use this to distinguish "💭 主动" style affordances from
normal replies. Proactive pushes do NOT thread to a user turn (they're
initiated by the persona) and therefore also carry
``in_reply_to_turn_id = None``.
"""


DeliveryKind = Literal["text", "voice_neutral"]
"""How the channel should deliver a reply.

MVP constraint (review R1): runtime only populates ``"text"`` and
``"voice_neutral"``. The LLM never chooses ``delivery`` — runtime sets
it from ``RuntimeContext.persona.voice_enabled``. Prosody variants
(tender / whisper tones) are deferred to v1.0 along with persona-selected
delivery; they will be re-added to this literal union at that time.
"""


@dataclass(frozen=True, slots=True)
class OutgoingMessage:
    """Typed envelope runtime hands to :meth:`Channel.send`.

    Carries only what a dumb I/O adapter needs. Persona state, mood and
    retrieval results are NOT in here — they have already been consumed
    by ``assemble_turn`` to produce ``content``.

    Stage 7 addition: ``voice_result`` carries the pre-generated voice
    artifact when ``delivery`` is ``"voice_neutral"``. Channels that
    support voice delivery (Web via SSE + HTTP endpoint, Discord via
    attachment upload) read this field and branch accordingly. When
    ``voice_result is None``, every channel defaults to text-only.
    """

    content: str
    in_reply_to: str | None = None
    in_reply_to_turn_id: str | None = None
    kind: OutgoingKind = "reply"
    delivery: DeliveryKind = "text"
    voice_result: VoiceResult | None = None


# ---------------------------------------------------------------------------
# Channel Protocol
# ---------------------------------------------------------------------------


@runtime_checkable
class Channel(Protocol):
    """Channel Protocol v0.2.

    Every transport adapter (web, cli, discord, imessage, wechat) must
    satisfy this shape. ``@runtime_checkable`` is used so tests can do
    ``isinstance(ch, Channel)`` as a structural smoke check.

    Required attributes:

    - ``channel_id``: stable opaque identifier, see spec §2.3
    - ``name``: human-readable label for logs and admin UI
    - ``in_flight_turn_id``: set by the runtime to the active turn id
      while ``assemble_turn`` is running; read by proactive's
      ``is_turn_in_flight`` gate (spec §17a.1 / proactive §3.5a)

    ``push_sse`` is explicitly **not** on the Protocol. It is an optional
    capability some channels implement and runtime detects via
    ``getattr(channel, "push_sse", None)``.
    """

    channel_id: str
    name: str
    in_flight_turn_id: str | None

    async def start(self) -> None:
        """Open sockets / connect to the external service. Idempotent."""

    async def stop(self) -> None:
        """Flush outgoing buffers, close sockets. Idempotent.

        After ``stop()`` returns, ``incoming()`` iterators must terminate
        cleanly on their next pull.
        """

    def incoming(self) -> AsyncIterator[IncomingTurn]:
        """Async-iterate debounced inbound turns.

        Even a single-message burst is wrapped in an ``IncomingTurn`` —
        there is no separate code path for the degenerate case.
        Implementations should hand turns off to this iterator from an
        internal queue so that transport-level backpressure does not
        block the runtime per-turn loop.
        """
        ...

    async def send(self, msg: OutgoingMessage) -> None:
        """Deliver a persona reply (or proactive push) to the transport.

        Runtime awaits this as part of the turn loop; implementations
        should return promptly and fan out to slow remote APIs via
        buffering / background tasks where appropriate.
        """

    async def on_turn_done(self, turn_id: str) -> None:
        """Runtime callback fired after the LLM finishes a turn.

        Signals the channel that ``in_flight_turn_id`` should be
        cleared and that any ``next_turn`` buffer may be promoted into
        ``current_turn``. Review M1 iron rule: promoted messages MUST
        go through the **normal** debounce timer, not flush immediately.

        Must be idempotent and must not raise — runtime may call this
        more than once for the same turn on recovery paths, and a
        failing callback does not roll back the LLM reply that
        triggered it.
        """


__all__ = [
    "IncomingMessage",
    "IncomingTurn",
    "OutgoingKind",
    "DeliveryKind",
    "OutgoingMessage",
    "Channel",
]
